### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ledge74** [JakeBednard/node-phea#2]
Hi, I'm trying to use your package with node 8 but it seems imports / exports are not supported. I tried using node 12 but I still get the same error. Any advice ? 

Thanks

```
/app/node_modules/phea/phea.js:3
import PheaEngine from './src/phea-engine';
       ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/index.js:5:14)
```

Edit : it seems the version available on the npm registry is not up to date compared to github

**Comment by JakeBednard** [comment]
I see you've that you've corrected the issue per Issue #3. I'll close this issue, and work with you in #3. Thanks.
